import type { Config } from 'tailwindcss';

/**
 * Design tokens ported from the original prototype (assets/js/tailwind.config.js)
 * so the React app keeps the exact same Material-3 / WhatsApp-green look.
 */
const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#191c1d',
        secondary: '#5f5e5e',
        'primary-fixed': '#66ff8e',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'surface-bright': '#f8f9fa',
        'surface-container-highest': '#e1e3e4',
        'on-tertiary-fixed': '#380d00',
        'surface-container': '#edeeef',
        tertiary: '#93492e',
        'on-background': '#191c1d',
        'secondary-fixed': '#e4e2e1',
        'on-secondary': '#ffffff',
        'surface-dim': '#d9dadb',
        'on-secondary-fixed-variant': '#474747',
        'error-container': '#ffdad6',
        'on-primary-container': '#005523',
        'secondary-fixed-dim': '#c8c6c6',
        outline: '#6c7b6b',
        'surface-variant': '#e1e3e4',
        'secondary-container': '#e4e2e1',
        'surface-tint': '#006d2f',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#002109',
        'on-primary-fixed-variant': '#005322',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#25d366',
        'primary-fixed-dim': '#3de273',
        'tertiary-container': '#ffa07e',
        'surface-container-high': '#e7e8e9',
        'inverse-primary': '#3de273',
        'on-surface-variant': '#3c4a3d',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        'on-tertiary-container': '#78351b',
        'on-secondary-fixed': '#1b1c1c',
        'surface-container-low': '#f3f4f5',
        surface: '#f8f9fa',
        'tertiary-fixed': '#ffdbcf',
        'outline-variant': '#bbcbb9',
        'tertiary-fixed-dim': '#ffb59b',
        'on-error': '#ffffff',
        primary: '#006d2f',
        'on-secondary-container': '#656464',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#763319',
        background: '#f8f9fa',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
      spacing: {
        'stack-md': '10px',
        'container-margin-mobile': '12px',
        'container-margin-desktop': '32px',
        gutter: '12px',
        base: '8px',
        'stack-sm': '4px',
        'stack-lg': '18px',
      },
      fontFamily: {
        'headline-sm': ['Montserrat'],
        'headline-md': ['Montserrat'],
        'headline-lg': ['Montserrat'],
        'display-lg': ['Montserrat'],
        'body-sm': ['Inter'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'label-sm': ['Inter'],
        'label-md': ['Inter'],
        'label-lg': ['Inter'],
      },
      // Scale trimmed ~15–25% from the original prototype for a denser, more
      // professional feel while preserving the type hierarchy.
      fontSize: {
        'headline-sm': ['16px', { lineHeight: '22px', fontWeight: '600' }],
        'headline-md': ['19px', { lineHeight: '26px', fontWeight: '600' }],
        'headline-lg': ['25px', { lineHeight: '32px', fontWeight: '700' }],
        'display-lg': ['36px', { lineHeight: '42px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '15px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-lg': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};

export default config;
